#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int callButton = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int callHistoryButton = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int emailLabel = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int emailText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int passwordLabel = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int passwordText = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int phoneNumberText = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int resultText = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int textView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int translateButton = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int validateActivityButton = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int validateButton = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Validate = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Call = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int CallHistoryButton = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int CallHistoryTitle = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int CallTo = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int CallToNumber = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Cancel = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ConvertButton = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int EmailLabel = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int PasswordLabel = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int ProvidePhoneNumber = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int Validate = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int ValidateActivity = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
